---
- name: playbook1
  hosts: server1
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Add a line to a file grub
    lineinfile:
      path: /etc/default/grub
      insertafter: '^#quet '
      regexp: '^#quet '
      line: "{{ item }}"
    with_items:
      - "net.ifnames=0"
      - "biosdevname=0"
  #- name:
   # shell: grub2-mkconfig