---
- name: playbook1
  hosts: server1
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Add a line to a file grub
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="crashkernel=auto'
      line: '\6 net.ifnames=0 biosdevname=0'
  #- name:
   # shell: grub2-mkconfig