---
- hosts: server1
  vars:
    http_host = node1.example.com

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    
    - name: start apache
      service:
        name: httpd
        state: started
    
    - name: Check for apache status
      service_facts:
    
    - name: See fact for apache
      debug:
        msg: "{{ ansible_facts.services['httpd.service'].state }}"
            
    - name: copy index test page
        template:
          src: "files/index.html.j2"
          dest: "/var/www/{{ http_host }}/index.html"

