---
- hosts: server1

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
      notify: start Apache
    
    #- name: start apache
    #  service:
     #   name: httpd
     #   state: started
     
    #  when: "{{ ansible_facts.services['httpd.service'].state }}" != "running"
    
    - name: Check for apache status
      service_facts:
    - name: See fact for apache
      debug:
        msg: "{{ ansible_facts.services['httpd.service'].state }}"

  handlers:
    - name: start Apache
      service:
        name: httpd
        state: start

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
