---
- hosts: server1

  tasks:
    - name: Install httpd2
      yum:
        name: httpd
        state: latest
    
    - name: start apache
      service:
        name: httpd
        state: started
    
    - name: Check for apache status
      service_facts:
    - name: See fact for apache
      debug:
        msg: "{{ ansible_facts.services }}"

  handlers:
    - name: start Apache
      service:
        name: apache2
        state: start

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
