---
- name: playbook3
  hosts: servers
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Add a line to a file grub
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="crashkernel='
      line: 'GRUB_CMDLINE_LINUX="crashkernel= auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet net.ifnames=0 biosdevname=0"'
  - name:
    shell: grub2-mkconfig